package core.com.rukh.green.panel;

import java.awt.event.ActionEvent;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author Rajan Prasad Upadhyay
 */
public class AbstractControlPanel extends javax.swing.JPanel {

    public BasePanel bPanel;
    static Logger logger = LogManager.getLogger(AbstractControlPanel.class.getName());

    //<editor-fold defaultstate="collapsed" desc="constructors">    
    
    public AbstractControlPanel(BasePanel parent) {
        this.bPanel = parent;
        initComponents();
    }

    //</editor-fold>
    public BasePanel getbPanel() {
        return bPanel;
    }

    public void setbPanel(BasePanel bPanel) {
        this.bPanel = bPanel;
    }

    
    @Override
    public void setVisible(boolean value) {
        super.setVisible(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(255, 0, 51));
        setLayout(new java.awt.BorderLayout());
        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

   //</editor-fold>
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public void OpenMenuItemActionPerformed(ActionEvent evt) {
        System.out.println("AbstractControlPanel : Open menu item clicked");
        
    }

    public void newProjectMenuItemActionPerformed(ActionEvent evt) {
        System.out.println("AbstractControlPanel : new Project menu item clicked");
    }

    public void executeMenuItemActionPerformed(ActionEvent evt) {
        System.out.println("AbstractControlPanel : execute menu item clicked");
    }

    public void exitMenuItemActionPerformed(ActionEvent evt) {
        System.out.println("AbstractControlPanel : exit menu item clicked");
    }

    public void saveMenuItemActionPerformed(ActionEvent evt) {
        System.out.println("AbstractControlPanel : save menu item clicked");
    }

}
